version: '3.7'

services:
  modelshare:
    image: modelshare
    container_name: modelshare
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
