
version: '3.7'

services:
  modelshare:
    image: modelshare
    container_name: modelshare
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 443
        published: 443
        protocol: tcp
        mode: host
