# This configuration is only applicable when deploying the application on the 
# Equinor Radix infrastructure. 
apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: modelshare
spec:
  environments:
    - name: dev
      build:
        from: develop
    - name: prod  
      build:
        from: master
  components:
    - name: application
      src: "./application"
      public: true
      ports:
       - name: http
         port: 80
      secrets:
        - CLIENT_SECRET
        - CLIENT_ID
        - TENANT_ID
        - REDIRECT_URI
        - AZURE_AD_GROUPS
        - STORAGE_PASSWORD
      environmentConfig:
        - environment: dev
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
        - environment: prod
          resources:
            requests:
              memory: "4Gi"
              cpu: "1000m"
  dnsAppAlias:
    environment: dev
    component: application
