apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: modelshare
spec:
  environments:
    - name: dev
      build:
        from: master
    - name: prod
  components:
    - name: application
      src: "./docker"
      publicPort: http
      ports:
       - name: http
         port: 80